### ISSUE TITLE
[NativeAOT-LLVM] MissingMethodException IncrementalValuesProvider after upgrading Microsoft.DotNet.ILCompiler.LLVM from 10.0.0-preview.2.25214.1 to 10.0.0-rc.1.26104.2

### ISSUE THREAD

**Issue by m-ringler** [dotnet/runtimelab#3234]
I'm using native-aot LLVM to compile a browser-wasm module with latest emsdk (5.0.0). After upgrading 

* Microsoft.DotNet.ILCompiler.LLVM
* runtime.browser-wasm.Microsoft.DotNet.ILCompiler.LLVM
* runtime.$(NETCoreSdkPortableRuntimeIdentifier).Microsoft.DotNet.ILCompiler.LLVM

from `10.0.0-preview.2.25214.1` to `10.0.0-rc.1.26104.2`

I am getting the compilation error

~~~
CSC : error CS8784: Generator 'ComClassGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'MissingMethodException' with message 'Method not found: 'Microsoft.CodeAnalysis.IncrementalValuesProvider`1<System.ValueTuple`2<!!0,!!1>> Microsoft.Interop.IncrementalValuesProviderExtensions.Zip(Microsoft.CodeAnalysis.IncrementalValuesProvider`1<!!0>, Microsoft.CodeAnalysis.IncrementalValuesProvider`1<!!1>)'.'. [/home/runner/work/straights/straights/Straights.Web/Straights.Web.csproj]
CSC : error CS8784: Generator 'ComInterfaceGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'MissingMethodException' with message 'Method not found: 'System.ValueTuple`2<Microsoft.CodeAnalysis.IncrementalValuesProvider`1<!!0>,Microsoft.CodeAnalysis.IncrementalValuesProvider`1<!!1>> Microsoft.Interop.DiagnosticOrTHelperExtensions.FilterAndReportDiagnostics(Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext, Microsoft.CodeAnalysis.IncrementalValuesProvider`1<Microsoft.Interop.DiagnosticOr`1<!!0>>, Microsoft.CodeAnalysis.IncrementalValuesProvider`1<!!1>)'.'. [/home/runner/work/straights/straights/Straights.Web/Straights.Web.csproj]
~~~

on a github ubuntu-latest runner with dotnet SDK '10.0.102'

See the [build log](https://github.com/user-attachments/files/25153768/job_log.txt) of build https://github.com/m-ringler/straights/actions/runs/21783231832/job/62850477975

The workflow.yml is at 
https://github.com/m-ringler/straights/blob/a437bfd82676e9837a54657cbf0bd85ac2e7d914/.github/workflows/straights-web.yml

And the Directory.Packages.props is at
https://github.com/m-ringler/straights/blob/a437bfd82676e9837a54657cbf0bd85ac2e7d914/Directory.Packages.props

The build succeeds when going back to `10.0.0-preview.2.25214.1` (see https://github.com/m-ringler/straights/actions/runs/21784087412/job/62852619140).

**Comment by SingleAccretion** [comment]
Thank you for reporting; I've also seen this when testing the new package locally but assumed it was some artifacts of using a preview SDK. Will investigate...

**Comment by SingleAccretion** [comment]
The latest packages now have the fix.
